/* Translation strings. Add a key here, then use data-i18n="key" on any element
   whose text should switch, or data-i18n-ph="key" on inputs for placeholders. */
const MFT_I18N = {
  en: {
    nav_home: "Home", nav_services: "Services", nav_gallery: "Gallery",
    nav_about: "About", nav_contact: "Contact", nav_order: "Get a Quote",

    hero_eyebrow: "Printing & Garments Accessories",
    hero_title: "Everything your production line needs, printed and packed right.",
    hero_lead: "M/S Fahim Traders supplies RMG factories and local businesses with hang tags, labels, packaging and print — ordered online, no showroom required.",
    hero_cta_order: "Request a Quote",
    hero_cta_services: "See Services",

    home_services_tag: "What we make",
    home_services_title: "Printing & accessories, under one roof",
    home_services_lead: "From a single woven label to a full packaging run, we handle the printing and finishing your line needs.",
    home_why_tag: "Why MFT",
    home_why_title: "Built for factories that can't wait",
    home_why_1_t: "Order online, any time",
    home_why_1_d: "No storefront, no waiting for a visit — send specs and quantities and we quote the same day.",
    home_why_2_t: "RMG-ready quality",
    home_why_2_d: "Care labels, hang tags and packaging finished to the tolerances garment buyers check for.",
    home_why_3_t: "One vendor, many products",
    home_why_3_d: "Labels, tags, cards, print and packaging from a single supplier means fewer vendors to manage.",
    home_cta_title: "Have specs ready?",
    home_cta_lead: "Send us your quantities and artwork and we'll come back with a quote.",

    services_eyebrow: "Services",
    services_title: "Complete printing & garments accessories solutions",
    services_lead: "Every item below is made to order. Photos and sample videos for each service are on the way — check back soon.",
    svc_hangtag_t: "Hang Tags", svc_hangtag_d: "Printed and die-cut hang tags for garments, in card stock and finishes to match your brand.",
    svc_care_t: "Care Labels", svc_care_d: "Wash-care and content labels, printed to compliance standards for RMG buyers.",
    svc_woven_t: "Woven Labels", svc_woven_d: "Woven main labels and size labels, damask or satin, in your brand colours.",
    svc_bcard_t: "Business Cards", svc_bcard_d: "Print and finishing for business cards — matte, gloss or textured stock.",
    svc_tshirt_t: "T-Shirt Printing", svc_tshirt_d: "Screen and DTF printing for T-shirts, single pieces or bulk orders.",
    svc_mug_t: "Mug Printing", svc_mug_d: "Custom sublimation printing on mugs for gifting or promotional use.",
    svc_banner_t: "Flex Banners", svc_banner_d: "Flex and vinyl banners for shop fronts, events and factory signage.",
    svc_box_t: "Packaging Boxes", svc_box_d: "Printed packaging and export cartons sized and branded to your product.",
    svc_media_soon: "Photos / video coming soon",

    gallery_eyebrow: "Gallery",
    gallery_title: "Our work, by category",
    gallery_lead: "This page is reserved for real photos and short videos of completed work. Placeholders below show where each category will sit.",
    gallery_filter_all: "All",
    gallery_upload_note: "Add images to /assets/gallery and swap each placeholder block for an <img> or <video> tag — see the comment in gallery.html.",

    about_eyebrow: "About Us",
    about_title: "A print & accessories partner for the RMG floor",
    about_lead: "M/S Fahim Traders was set up to give garment factories and local businesses one dependable place to order printing and accessories — without needing a physical shop to visit.",
    about_prop_t: "Proprietor",
    about_mission_t: "What we focus on",
    about_mission_d: "Consistent quality on repeat orders, clear pricing, and turnaround that matches production schedules — not the other way around.",
    about_how_t: "How ordering works",
    about_how_1: "Share your specs, quantity and artwork over call, WhatsApp or email.",
    about_how_2: "We confirm pricing, materials and turnaround.",
    about_how_3: "Production runs, and finished goods are delivered to you.",

    contact_eyebrow: "Contact",
    contact_title: "Tell us what you need printed",
    contact_lead: "Reach out directly, or send your specs through the form and we'll reply with a quote.",
    contact_phone: "Phone", contact_email: "Email", contact_hours: "Hours",
    contact_hours_v: "Sun–Thu, 9:00 AM – 7:00 PM",
    form_name: "Full name", form_company: "Company / Factory",
    form_phone: "Phone number", form_service: "Service needed",
    form_qty: "Approx. quantity", form_message: "Details / specifications",
    form_submit: "Send Request",
    form_note: "This form doesn't send automatically yet — connect it to email or WhatsApp before publishing the site.",

    footer_tagline: "Complete printing & garments accessories solutions.",
    footer_pages_t: "Pages", footer_services_t: "Services", footer_contact_t: "Contact",
    footer_rights: "All rights reserved.",
  },
  bn: {
    nav_home: "হোম", nav_services: "সার্ভিসেস", nav_gallery: "গ্যালারি",
    nav_about: "আমাদের সম্পর্কে", nav_contact: "যোগাযোগ", nav_order: "কোটেশন চান",

    hero_eyebrow: "প্রিন্টিং ও গার্মেন্টস অ্যাক্সেসরিজ",
    hero_title: "আপনার প্রোডাকশন লাইনের জন্য যা কিছু দরকার, সঠিকভাবে প্রিন্ট ও প্যাক করা।",
    hero_lead: "এম/এস ফাহিম ট্রেডার্স আরএমজি ফ্যাক্টরি ও স্থানীয় ব্যবসাগুলোকে হ্যাং ট্যাগ, লেবেল, প্যাকেজিং ও প্রিন্ট সরবরাহ করে — অনলাইনে অর্ডার, কোনো শোরুম ছাড়াই।",
    hero_cta_order: "কোটেশন চান",
    hero_cta_services: "সার্ভিসেস দেখুন",

    home_services_tag: "আমরা যা তৈরি করি",
    home_services_title: "প্রিন্টিং ও অ্যাক্সেসরিজ, এক ছাদের নিচে",
    home_services_lead: "একটি ওভেন লেবেল থেকে শুরু করে সম্পূর্ণ প্যাকেজিং পর্যন্ত, আপনার লাইনের প্রয়োজনীয় প্রিন্টিং ও ফিনিশিং আমরা সামলাই।",
    home_why_tag: "কেন এমএফটি",
    home_why_title: "যারা অপেক্ষা করতে পারে না তাদের জন্য তৈরি",
    home_why_1_t: "যেকোনো সময় অনলাইনে অর্ডার",
    home_why_1_d: "কোনো শোরুম নেই, ভিজিটের অপেক্ষা নেই — স্পেসিফিকেশন ও পরিমাণ পাঠান, একই দিনে কোটেশন পাবেন।",
    home_why_2_t: "আরএমজি-মানের গুণমান",
    home_why_2_d: "কেয়ার লেবেল, হ্যাং ট্যাগ ও প্যাকেজিং সেই মানে তৈরি যা বায়াররা যাচাই করেন।",
    home_why_3_t: "একটি ভেন্ডার, অনেক পণ্য",
    home_why_3_d: "লেবেল, ট্যাগ, কার্ড, প্রিন্ট ও প্যাকেজিং একজন সরবরাহকারীর কাছ থেকে — কম ভেন্ডার সামলাতে হয়।",
    home_cta_title: "স্পেসিফিকেশন প্রস্তুত?",
    home_cta_lead: "আপনার পরিমাণ ও আর্টওয়ার্ক পাঠান, আমরা কোটেশন নিয়ে ফিরে আসব।",

    services_eyebrow: "সার্ভিসেস",
    services_title: "সম্পূর্ণ প্রিন্টিং ও গার্মেন্টস অ্যাক্সেসরিজ সমাধান",
    services_lead: "নিচের প্রতিটি আইটেম অর্ডার অনুযায়ী তৈরি করা হয়। প্রতিটি সার্ভিসের ছবি ও নমুনা ভিডিও শীঘ্রই যুক্ত হবে।",
    svc_hangtag_t: "হ্যাং ট্যাগ", svc_hangtag_d: "গার্মেন্টসের জন্য প্রিন্টেড ও ডাই-কাট হ্যাং ট্যাগ, আপনার ব্র্যান্ডের সাথে মিলিয়ে।",
    svc_care_t: "কেয়ার লেবেল", svc_care_d: "ওয়াশ-কেয়ার ও কনটেন্ট লেবেল, আরএমজি বায়ারদের মান অনুযায়ী প্রিন্টেড।",
    svc_woven_t: "ওভেন লেবেল", svc_woven_d: "ওভেন মেইন লেবেল ও সাইজ লেবেল, ড্যামাস্ক বা সাটিন, আপনার ব্র্যান্ড কালারে।",
    svc_bcard_t: "বিজনেস কার্ড", svc_bcard_d: "বিজনেস কার্ডের প্রিন্ট ও ফিনিশিং — ম্যাট, গ্লস বা টেক্সচার্ড স্টক।",
    svc_tshirt_t: "টি-শার্ট প্রিন্টিং", svc_tshirt_d: "টি-শার্টের জন্য স্ক্রিন ও ডিটিএফ প্রিন্টিং, একক বা বাল্ক অর্ডার।",
    svc_mug_t: "মগ প্রিন্টিং", svc_mug_d: "উপহার বা প্রমোশনের জন্য মগে কাস্টম সাবলিমেশন প্রিন্ট।",
    svc_banner_t: "ফ্লেক্স ব্যানার", svc_banner_d: "দোকান, অনুষ্ঠান ও ফ্যাক্টরি সাইনেজের জন্য ফ্লেক্স ও ভিনাইল ব্যানার।",
    svc_box_t: "প্যাকেজিং বক্স", svc_box_d: "আপনার পণ্যের মাপ ও ব্র্যান্ডিং অনুযায়ী প্রিন্টেড প্যাকেজিং ও এক্সপোর্ট কার্টন।",
    svc_media_soon: "ছবি / ভিডিও শীঘ্রই আসছে",

    gallery_eyebrow: "গ্যালারি",
    gallery_title: "আমাদের কাজ, ক্যাটাগরি অনুযায়ী",
    gallery_lead: "এই পেজটি সম্পন্ন কাজের প্রকৃত ছবি ও সংক্ষিপ্ত ভিডিওর জন্য সংরক্ষিত। নিচের প্লেসহোল্ডারগুলো দেখাচ্ছে প্রতিটি ক্যাটাগরি কোথায় বসবে।",
    gallery_filter_all: "সব",
    gallery_upload_note: "/assets/gallery ফোল্ডারে ছবি যোগ করুন এবং প্রতিটি প্লেসহোল্ডার ব্লককে <img> বা <video> ট্যাগ দিয়ে পরিবর্তন করুন — gallery.html-এর কমেন্ট দেখুন।",

    about_eyebrow: "আমাদের সম্পর্কে",
    about_title: "আরএমজি ফ্লোরের জন্য প্রিন্ট ও অ্যাক্সেসরিজ পার্টনার",
    about_lead: "এম/এস ফাহিম ট্রেডার্স গার্মেন্ট ফ্যাক্টরি ও স্থানীয় ব্যবসাগুলোকে প্রিন্টিং ও অ্যাক্সেসরিজ অর্ডার করার একটি নির্ভরযোগ্য জায়গা দিতে গড়ে উঠেছে — কোনো দোকানে যাওয়ার প্রয়োজন ছাড়াই।",
    about_prop_t: "প্রোপ্রাইটর",
    about_mission_t: "আমরা যেখানে মনোযোগ দিই",
    about_mission_d: "বারবার অর্ডারে একই মান, স্পষ্ট মূল্য, এবং প্রোডাকশন শিডিউলের সাথে মিলিয়ে ডেলিভারি সময়।",
    about_how_t: "অর্ডার যেভাবে হয়",
    about_how_1: "কল, হোয়াটসঅ্যাপ বা ইমেইলে স্পেসিফিকেশন, পরিমাণ ও আর্টওয়ার্ক পাঠান।",
    about_how_2: "আমরা মূল্য, উপকরণ ও সময়সীমা নিশ্চিত করি।",
    about_how_3: "প্রোডাকশন শুরু হয়, এবং তৈরি পণ্য আপনার কাছে পৌঁছে দেওয়া হয়।",

    contact_eyebrow: "যোগাযোগ",
    contact_title: "আপনার প্রিন্টের প্রয়োজন জানান",
    contact_lead: "সরাসরি যোগাযোগ করুন, বা ফর্মের মাধ্যমে স্পেসিফিকেশন পাঠান — আমরা কোটেশন সহ উত্তর দেব।",
    contact_phone: "ফোন", contact_email: "ইমেইল", contact_hours: "সময়",
    contact_hours_v: "রবি–বৃহস্পতি, সকাল ৯টা – রাত ৭টা",
    form_name: "পূর্ণ নাম", form_company: "কোম্পানি / ফ্যাক্টরি",
    form_phone: "ফোন নম্বর", form_service: "প্রয়োজনীয় সার্ভিস",
    form_qty: "আনুমানিক পরিমাণ", form_message: "বিস্তারিত / স্পেসিফিকেশন",
    form_submit: "রিকোয়েস্ট পাঠান",
    form_note: "এই ফর্মটি এখনো স্বয়ংক্রিয়ভাবে পাঠায় না — সাইট পাবলিশ করার আগে ইমেইল বা হোয়াটসঅ্যাপের সাথে সংযুক্ত করুন।",

    footer_tagline: "সম্পূর্ণ প্রিন্টিং ও গার্মেন্টস অ্যাক্সেসরিজ সমাধান।",
    footer_pages_t: "পেজ", footer_services_t: "সার্ভিসেস", footer_contact_t: "যোগাযোগ",
    footer_rights: "সর্বস্বত্ব সংরক্ষিত।",
  }
};
